<a href="https://colab.research.google.com/github/schesnowitz/DeepLearningProject/blob/main/colab/transposing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch
import numpy as np


# create vector
np_vector = np.array([[1,2,3,4]])
print(np_vector), print('  ')


# transpose
print(np_vector.T), print('  ')

# transpose the transpose
np_vectorT = np_vector.T
print(f"{np_vectorT.T} \n")

# same for a matrix
np_matrix = np.array([
                        [1,2,3,4],
                        [5,6,7,8]
                    ])
print(f"{np_matrix}\n")

# transposed matrix
print(f"{np_matrix.T}\n")

# and back again
npmT = np_matrix.T
print(f"{npmT.T}\n")

[[1 2 3 4]]
  
[[1]
 [2]
 [3]
 [4]]
  
[[1 2 3 4]] 

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]



using numpy

In [12]:
# create vector
torch_vect = torch.tensor([[1,2,3,4]])
print(f"{torch_vect}\n")


# transpose
print(f"{torch_vect.T}\n")

# transpose the transpose
torch_vectT = torch_vect.T
print(f"{torch_vectT.T} \n")

# same for a matrix
torch_matrix = torch.tensor([
                        [1,2,3,4],
                        [5,6,7,8]
                    ])
print(f"{torch_matrix}\n")

# transposed matrix
print(f"{torch_matrix.T}\n")

# and back again
torch_matrixT = torch_matrix.T
print(f"{torch_matrixT.T}\n")

tensor([[1, 2, 3, 4]])

tensor([[1],
        [2],
        [3],
        [4]])

tensor([[1, 2, 3, 4]]) 

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

